### ISSUE TITLE
Woolworths Rewards API integration

### ISSUE THREAD

**Issue by pl4nty** [MattTimms/up_woolies#1]
I've recently reverse-engineered the `api.woolworthsrewards.com.au` v2 authentication process. I don't use Up Bank myself, but happy to provide details if you're still interested - I'm pl4nty#5958 on Discord.

**Comment by MattTimms** [comment]
The endpoint worked like a charm... until one day it started returning 403s 😓
Changes to support user/pass login were added in recent release [v1.1.0](https://github.com/MattTimms/up_woolies/releases/tag/v1.1.0)
