### ISSUE TITLE
I love it 

### ISSUE THREAD

**Issue by ravi0the0sun** [MattTimms/up_woolies#2]
Like the smart receipt from afterpay purchase.
![Screenshot_20220206-215733_Up.jpg](https://user-images.githubusercontent.com/28498241/152677644-1bbb3d46-df8e-4648-a617-a2f84f35e22e.jpg)

**Comment by MattTimms** [comment]
Thanks! 🙏 Yeah, exactly like that, which Up's founder, Dom Pym, talks a bit about [here](https://twitter.com/dompym/status/1418792235559235589?s=20&t=JC8zPxu9MxWIAxsd1mLY1Q).
