### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by kkozmic** [MattTimms/up_woolies#3]
Hi @MattTimms, love your work here.

I was just digging into a similar problem over the holiday break, trying to import Woolies transactions into my expenses spreadsheet.
Rather than reimplementing the whole API dance myself I'd be keen to fork this repo and use it as my starting point but I can't see what license you've used here.
Would you mind adding one?

**Comment by MattTimms** [comment]
Yeah, of course. [v1.3.1](https://github.com/MattTimms/up_woolies/releases/tag/v1.3.1) includes an MIT license.
